### ISSUE TITLE
Black text (zsh autocomplete)

### ISSUE THREAD

**Issue by jenslys** [MartinRybergLaude/zed-theme-codesandbox#1]
This might be niche, but when getting autocompletions from zsh, the text is black which makes it hard to see.

zed with codesandbox:

https://github.com/MartinRybergLaude/zed-theme-codesandbox/assets/69081683/0cc22c22-1436-4853-80f3-a9e52f765a3a

Vscode with codesandbox:
![Screenshot 2024-06-08 at 14 21 32](https://github.com/MartinRybergLaude/zed-theme-codesandbox/assets/69081683/e936b80e-b1f3-4344-b685-e7bface8a864)

**Comment by MartinRybergLaude** [comment]
Nice catch! Fixing asap.

**Comment by MartinRybergLaude** [comment]
Fixed in [this PR](https://github.com/zed-industries/extensions/pull/913), should go live as soon as it's merged.

**Comment by jenslys** [comment]
also found this, dont know if the pr fixes it:

![Screenshot 2024-06-08 at 18 38 06@2x](https://github.com/MartinRybergLaude/zed-theme-codesandbox/assets/69081683/e3e39609-e200-49d4-b5d7-4f8eb2f00ecf)

**Comment by MartinRybergLaude** [comment]
Fixed and published
