### ISSUE TITLE
Discrepancies between zed and vscode version

### ISSUE THREAD

**Issue by jenslys** [MartinRybergLaude/zed-theme-codesandbox#2]
# Found some small discrepancies, some might be small, but others makes the code 2x easier to read.

## Inline ai code suggestions are white in zed, and a more subtle color in vscode

zed:
![Screenshot 2024-06-14 at 20 44 47@2x](https://github.com/MartinRybergLaude/zed-theme-codesandbox/assets/69081683/a86a4bfb-b364-41a6-884f-80f76a1d145a)

vscode:
![Screenshot 2024-06-14 at 20 45 48@2x](https://github.com/MartinRybergLaude/zed-theme-codesandbox/assets/69081683/67a43431-9d94-400d-8b50-adf66e2da51e)

## other

zed:
![Screenshot 2024-06-14 at 20 47 58@2x](https://github.com/MartinRybergLaude/zed-theme-codesandbox/assets/69081683/a6175af3-9b7c-45e3-af22-c8d89e5fc07e)

vscode:

![Screenshot 2024-06-14 at 20 48 15@2x](https://github.com/MartinRybergLaude/zed-theme-codesandbox/assets/69081683/08685bef-1035-4ba7-b605-07221a822c02)

## other 2

zed:

![Screenshot 2024-06-14 at 20 50 40@2x](https://github.com/MartinRybergLaude/zed-theme-codesandbox/assets/69081683/6ad15495-51a3-4c6f-b3bf-8695a920965c)

vscode:
![Screenshot 2024-06-14 at 20 50 28@2x](https://github.com/MartinRybergLaude/zed-theme-codesandbox/assets/69081683/9bcb9f26-1558-4128-859e-f537dd74feac)

## other 3

zed:
![Screenshot 2024-06-14 at 20 51 58@2x](https://github.com/MartinRybergLaude/zed-theme-codesandbox/assets/69081683/aeb7b5db-cf53-4a87-9b74-7cb67530b647)

vscode:

![Screenshot 2024-06-14 at 20 51 44@2x](https://github.com/MartinRybergLaude/zed-theme-codesandbox/assets/69081683/fa4a6e08-1a26-45f4-b778-44fa3b7c0bc8)

## other 4

zed:
![Screenshot 2024-06-14 at 20 53 38@2x](https://github.com/MartinRybergLaude/zed-theme-codesandbox/assets/69081683/83ee7705-1b2a-4ccd-abc5-969ff888f8ec)

vscode:

![Screenshot 2024-06-14 at 20 54 10@2x](https://github.com/MartinRybergLaude/zed-theme-codesandbox/assets/69081683/1cbc3cca-4758-4a92-855d-e96c76522426)

## other 5

zed:
![Screenshot 2024-06-14 at 20 56 08@2x](https://github.com/MartinRybergLaude/zed-theme-codesandbox/assets/69081683/6b686b5f-f1fd-43f4-8d88-93752eaab40c)

vscode:
![Screenshot 2024-06-14 at 20 55 32@2x](https://github.com/MartinRybergLaude/zed-theme-codesandbox/assets/69081683/e4324bbf-9cef-4fbc-bf0c-3d790a6e9a83)

**Comment by MartinRybergLaude** [comment]
Nice! Thanks for the screenshots with discrepancies, that'll help.

For context as to why there are quite a few of these, it's because I used zed's tool to convert vscode themes automatically for the most part. Clearly it isn't quite there yet 😅

**Comment by MartinRybergLaude** [comment]
Digged around a bit and it turns out Zed's theming system isn't nearly as advanced as vscode's unfortunately. 

I can fix predictive text and turn jsx tags purple, but the same color will always be used for tags and function names for instance, so the chartreuse color used for function names in the vscode version can't be applied in zed for functions (unless the jsx tags are chartreuse too).

Something like this is the best I can do from what I can tell:

![screen 2024-06-14 at 23 39 59](https://github.com/MartinRybergLaude/zed-theme-codesandbox/assets/32536904/656561dc-2199-4d48-a49a-10251147206a)

**Comment by MartinRybergLaude** [comment]
Above fixes coming in https://github.com/zed-industries/extensions/pull/931

**Comment by MartinRybergLaude** [comment]
Merged to the zed repo. Closing until zed's theme engine gets advanced enough for better replication of the VSCode theme.
